language: python

python: 3.6

sudo: required

matrix:
  include:
    - env: CC=gcc    

before_install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -qq
  - sudo apt-get install libcurl3  
  - sudo apt-get install autoconf-archive  
  - sudo apt-get install pkg-config
  - wget -c http://bitbucket.org/eigen/eigen/get/3.2.9.tar.bz2 -O eigen-3.2.9.tar.bz2
  - bzip2 -d eigen-3.2.9.tar.bz2
  - tar xvf eigen-3.2.9.tar
  - mv eigen-eigen-* eigen 
  - mkdir eigbuild && cd eigbuild && cmake ../eigen && sudo make install && cd ..
  - rm -rf eigen-3.2.9.tar*
 
install:
  - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip install meson
  - pip install conan

script:
  - mkdir builddir && cd builddir
  - conan install ..
