language: cpp

sudo: required

before_install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -qq
  - sudo apt-get install libcurl3
  - sudo apt-get install --only-upgrade autoconf
  - sudo apt-get install --only-upgrade automake
  - sudo apt-get install --only-upgrade autotools-dev
  - sudo apt-get install autoconf-archive  
  - sudo apt-get install pkg-config
  - wget -c http://bitbucket.org/eigen/eigen/get/3.2.9.tar.bz2 -O eigen-3.2.9.tar.bz2
  - bzip2 -d eigen-3.2.9.tar.bz2
  - tar xvf eigen-3.2.9.tar
  - mv eigen-eigen-* eigen 
  - mkdir eigbuild && cd eigbuild && cmake ../eigen && sudo make install && cd ..
  - rm -rf eigen-3.2.9.tar*
 
before_script:
  - autoreconf -vif

script:
  - ./configure CXXFLAGS=-coverage && make check

after_success:
    - ./cstat_tests
    - cd tests && gcov cstat_tests-test.gcda && gcov cstat_tests-test.gcno
    - bash <(curl -s https://codecov.io/bash)
