#!/bin/bash

echo "Cleaning up..."


rm -rf Makefile
rm -rf Makefile.in
rm -rf aclocal.m4
rm -rf autom4te.cache/
rm -rf compile
rm -rf config.*
rm -rf configure
rm -rf depcomp
rm -rf install-sh
rm -rf missing
rm -rf stamp-h1
rm -rf test-driver
rm -rf cstat_tests*
rm -rf test-suite.log
rm -rf tests/*.o
rm -rf tests/*.so
rm -rf tests/stamp-h1
rm -rf tests/.deps/
 
find . -name config.h -delete
find . -name stamp-h1 -delete
find . -name *.a -delete
find . -name *.o -delete
find . -name *.dirstamp -delete
find . -name '.DS_Store' -type f -delete

